title: Songran Liu (刘松冉)
logo: /assets/img/logo1.jpg
description: - Email: liusongran@cse.neu.edu.cn
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
#theme: jekyll-theme-minimal

#footer-links:
#  zhihu: ll-chen-2
#  email: mailto:liusongran@cse.neu.edu.cn
#  github: liusongran
