DSEG	SEGMENT
STR		DB	'I  live  in  Shenyang',00H
LEN		DB	?
DSEG	ENDS
CSEG	SEGMENT
		ASSUME  CS:CSEG,DS:DSEG
SLEN:	MOV		AX,DSEG
		MOV		DS,AX
		LEA		SI,STR
		XOR		AL,AL
LOP:	CMP		BYTE  PTR[SI],00H
		JZ		DONE
		INC		AL
		INC		SI
		JMP		LOP
DONE:	MOV		LEN,AL
		MOV		AH,4CH
		INT		21H
CSEG	ENDS
		END		SLEN
