DSEG	SEGMENT
LIST	DW		503,87,512,61,908,170,897,275
LLNT	DB		8
DSEG	ENDS

CSEG	SEGMENT
		ASSUME 	CS:CSEG, DS:DSEG
START:	MOV		AX,DSEG
		MOV		DS,AX
		MOV		CH,LLNT
		DEC		CH
EXCH1:	LEA		SI,LIST
		MOV		CL,CH
		XOR		BL,BL
EXCH2:	MOV		AX,[SI]
		CMP		AX,[SI+2]
		JBE		EXCH3
		MOV		DX,[SI+2]
		MOV		[SI+2],AX
		MOV		[SI],DX
		OR		BL,01
EXCH3:	ADD		SI,2
		DEC		CL
		JNZ		EXCH2
		AND		BL,BL
		JZ		STOP
		DEC		CH
		JNZ		EXCH1
STOP:	MOV		AH,4CH
		INT		21H
CSEG	ENDS
		END		START
