;多字节数据比较子程序MCMP
MCMP	PROC
        PUSH	SI
        PUSH	AX
        PUSH	DI
MCMP1:  MOV	AL,[SI]
        CMP	AL,[DI]
        JNZ	MCMPR
        DEC	SI
        DEC	DI
        DEC	AH
        JNZ	MCMP1
MCMPR:  POP	DI
        POP	AX
        POP	SI
        RET
MCMP	ENDP

;多字节数据相减子程序MSUB
MSUB    PROC
        PUSH	SI
        PUSH	AX
        PUSH	DI
        CLC
MSUB1: 	MOV	AL,[DI]
        SBB	[SI],AL
        INC	SI
        INC	DI
        DEC	AH
        JNZ	MSUB1
        POP	DI
        POP	AX
        POP	SI
        RET
MCMP	ENDP

;多字节数据左移一位子程序MSHL
MSHL    PROC
        PUSH	SI
        PUSH	CX
        CLC
MSHL1:	RCL     BYTE  PTR  [SI],1
        INC     SI
        DEC     CH
        JNZ     MSHL1
        POP     CX
        POP     SI
        RET
MCMP	ENDP

DSEG	SEGMENT
DIVND	DB      5FH,0D4H,0E4H,0DCH,68H,1DH
DIVOR	DB      85H,27H,4AH
DIVM	DW      6
DIVN	DW      3
QUON	DW      0
QUO	DB      3  DUP (0)
REM	DB      3  DUP (0)
DSEG	ENDS
SSEG	SEGMENT STACK
STK	DB      20  DUP (0)
SSEG	ENDS
CSEG	SEGMENT
	ASSUME  CS:CSEG,DS:DSEG
	ASSUME  ES:DSEG,SS:SSEG
START:	MOV     AX,DSEG
	MOV     DS,AX
	MOV     ES,AX
	MOV     AX,SSEG
	MOV     SS,AX
	MOV     SP,SIZE  STK
	LEA	SI,DIVND
	MOV	BX,SI
	ADD	BX,DIVM
	DEC	BX
	LEA	DI,DIVOR
	MOV	DX,DI
	ADD	DX,DIVN
	DEC	DX
	MOV	CX,DIVM
	SUB	CX,DIVN
	MOV	QUON,CX
	ADD	CX,CX
	ADD	CX,CX 	
	ADD	CX,CX
	MOV	CH,BYTE  PTR  DIVM
	MOV	AH,BYTE  PTR  DIVN
	XCHG	SI,BX
	XCHG	DI,DX
	CALL	MCMP
	XCHG	BX,SI
	XCHG	DX,DI
	JNC	OVER
MDIV1:	CALL	MSHL	
	XCHG	BX,SI
	XCHG	DX,DI
	CALL	MCMP
	XCHG	BX,SI
	XCHG	DX,DI
	JC	CHCNT
	ADD	SI,QUON
	CALL	MSUB
	SUB	SI,QUON
	INC	BYTE  PTR  [SI]
CHCNT:	DEC	CL
	JNZ	MDIV1
	MOV	CX,DIVM
	LEA	DI,QUO
	REP	MOVSB
	JMP	EXIT
OVER:	MOV	AL,0FFH
	LEA	DI,QUO
	MOV	CX,DIVM
	REP	STOSB
EXIT:	MOV	AH,4CH
	INT	21H
CSEG	ENDS
	END	START


