;*****EXAM7.2*****
DSEG	SEGMENT
DATA	DB	15H,26H,03H,8AH,11H,...
DTEND	DB	62H
MAX	DB	0
DSEG	ENDS

SSEG	SEGMENT STACK
STACK	DB	50  DUP(0)
SSEG	ENDS

CSEG	SEGMENT
		ASSUME	CS:CSEG,DS:DSEG
		ASSUME	SS:SSEG
SMAX:	MOV		AX, DSEG
		MOV		DS, AX
		MOV		AX, SSEG
		MOV		SS, AX
		MOV		SP, SIZE STACK
		LEA		SI, DATA
		MOV		AL, [SI]		;取第一个数据
AG:		INC		SI				;指向下一个数据
		CMP		SI, OFFSET DTEND
		JA		LOAD			;指针大于末址
		CMP		AL, [SI]		;两数比较
		JA		AG				;AL中数大，转
		MOV		AL, [SI]		;大数→AL
		JMP		AG				;转，继续执行
LOAD:	MOV		MAX, AL			;保存最大值
		MOV		AH, 4CH
		INT		21H
CSEG	ENDS
END	SMAX

